/*
* generated by Xtext
*/
package net.langleystudios.dsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;


@Singleton
public class AvroSchemaGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class AvroSchemaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AvroSchema");
		private final Assignment cTypesAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cTypesAlternatives_0 = (Alternatives)cTypesAssignment.eContents().get(0);
		private final RuleCall cTypesJsonTypeParserRuleCall_0_0 = (RuleCall)cTypesAlternatives_0.eContents().get(0);
		private final RuleCall cTypesRecordTypeParserRuleCall_0_1 = (RuleCall)cTypesAlternatives_0.eContents().get(1);
		private final RuleCall cTypesUnionTypeParserRuleCall_0_2 = (RuleCall)cTypesAlternatives_0.eContents().get(2);
		
		//AvroSchema:
		//	types+=(JsonType | RecordType | UnionType);
		public ParserRule getRule() { return rule; }

		//types+=(JsonType | RecordType | UnionType)
		public Assignment getTypesAssignment() { return cTypesAssignment; }

		//JsonType | RecordType | UnionType
		public Alternatives getTypesAlternatives_0() { return cTypesAlternatives_0; }

		//JsonType
		public RuleCall getTypesJsonTypeParserRuleCall_0_0() { return cTypesJsonTypeParserRuleCall_0_0; }

		//RecordType
		public RuleCall getTypesRecordTypeParserRuleCall_0_1() { return cTypesRecordTypeParserRuleCall_0_1; }

		//UnionType
		public RuleCall getTypesUnionTypeParserRuleCall_0_2() { return cTypesUnionTypeParserRuleCall_0_2; }
	}

	public class UnionTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UnionType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypesUnionMemberParserRuleCall_1_0 = (RuleCall)cTypesAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cTypesAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cTypesUnionMemberParserRuleCall_2_1_0 = (RuleCall)cTypesAssignment_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//UnionType:
		//	"[" types+=UnionMember ("," types+=UnionMember)* "]";
		public ParserRule getRule() { return rule; }

		//"[" types+=UnionMember ("," types+=UnionMember)* "]"
		public Group getGroup() { return cGroup; }

		//"["
		public Keyword getLeftSquareBracketKeyword_0() { return cLeftSquareBracketKeyword_0; }

		//types+=UnionMember
		public Assignment getTypesAssignment_1() { return cTypesAssignment_1; }

		//UnionMember
		public RuleCall getTypesUnionMemberParserRuleCall_1_0() { return cTypesUnionMemberParserRuleCall_1_0; }

		//("," types+=UnionMember)*
		public Group getGroup_2() { return cGroup_2; }

		//","
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }

		//types+=UnionMember
		public Assignment getTypesAssignment_2_1() { return cTypesAssignment_2_1; }

		//UnionMember
		public RuleCall getTypesUnionMemberParserRuleCall_2_1_0() { return cTypesUnionMemberParserRuleCall_2_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_3() { return cRightSquareBracketKeyword_3; }
	}

	public class UnionMemberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UnionMember");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cRecordTypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cArrayTypeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cPrimitiveParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cMapTypeParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cEnumTypeParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cFixedTypeParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final Group cGroup_6 = (Group)cAlternatives.eContents().get(6);
		private final Keyword cQuotationMarkKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cRecordRefAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cRecordRefRecordCrossReference_6_1_0 = (CrossReference)cRecordRefAssignment_6_1.eContents().get(0);
		private final RuleCall cRecordRefRecordIDTerminalRuleCall_6_1_0_1 = (RuleCall)cRecordRefRecordCrossReference_6_1_0.eContents().get(1);
		private final Keyword cQuotationMarkKeyword_6_2 = (Keyword)cGroup_6.eContents().get(2);
		
		//UnionMember:
		//	RecordType | ArrayType | Primitive | MapType | EnumType | FixedType | "\"" recordRef=[Record] "\"";
		public ParserRule getRule() { return rule; }

		//RecordType | ArrayType | Primitive | MapType | EnumType | FixedType | "\"" recordRef=[Record] "\""
		public Alternatives getAlternatives() { return cAlternatives; }

		//RecordType
		public RuleCall getRecordTypeParserRuleCall_0() { return cRecordTypeParserRuleCall_0; }

		//ArrayType
		public RuleCall getArrayTypeParserRuleCall_1() { return cArrayTypeParserRuleCall_1; }

		//Primitive
		public RuleCall getPrimitiveParserRuleCall_2() { return cPrimitiveParserRuleCall_2; }

		//MapType
		public RuleCall getMapTypeParserRuleCall_3() { return cMapTypeParserRuleCall_3; }

		//EnumType
		public RuleCall getEnumTypeParserRuleCall_4() { return cEnumTypeParserRuleCall_4; }

		//FixedType
		public RuleCall getFixedTypeParserRuleCall_5() { return cFixedTypeParserRuleCall_5; }

		//"\"" recordRef=[Record] "\""
		public Group getGroup_6() { return cGroup_6; }

		//"\""
		public Keyword getQuotationMarkKeyword_6_0() { return cQuotationMarkKeyword_6_0; }

		//recordRef=[Record]
		public Assignment getRecordRefAssignment_6_1() { return cRecordRefAssignment_6_1; }

		//[Record]
		public CrossReference getRecordRefRecordCrossReference_6_1_0() { return cRecordRefRecordCrossReference_6_1_0; }

		//ID
		public RuleCall getRecordRefRecordIDTerminalRuleCall_6_1_0_1() { return cRecordRefRecordIDTerminalRuleCall_6_1_0_1; }

		//"\""
		public Keyword getQuotationMarkKeyword_6_2() { return cQuotationMarkKeyword_6_2; }
	}

	public class JsonTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "JsonType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cQuotationMarkKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cQuotationMarkKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTypeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTypePrimitiveParserRuleCall_6_0 = (RuleCall)cTypeAssignment_6.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//JsonType:
		//	"{" "\"" "type" "\"" ":" "\"" type=Primitive "\"" "}";
		public ParserRule getRule() { return rule; }

		//"{" "\"" "type" "\"" ":" "\"" type=Primitive "\"" "}"
		public Group getGroup() { return cGroup; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }

		//"\""
		public Keyword getQuotationMarkKeyword_1() { return cQuotationMarkKeyword_1; }

		//"type"
		public Keyword getTypeKeyword_2() { return cTypeKeyword_2; }

		//"\""
		public Keyword getQuotationMarkKeyword_3() { return cQuotationMarkKeyword_3; }

		//":"
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }

		//"\""
		public Keyword getQuotationMarkKeyword_5() { return cQuotationMarkKeyword_5; }

		//type=Primitive
		public Assignment getTypeAssignment_6() { return cTypeAssignment_6; }

		//Primitive
		public RuleCall getTypePrimitiveParserRuleCall_6_0() { return cTypePrimitiveParserRuleCall_6_0; }

		//"\""
		public Keyword getQuotationMarkKeyword_7() { return cQuotationMarkKeyword_7; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class RecordTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RecordType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cQuotationMarkKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cQuotationMarkKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cRecordKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cQuotationMarkKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cQuotationMarkKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cNameKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cQuotationMarkKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cColonKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cQuotationMarkKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cNameAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cNameIDTerminalRuleCall_14_0 = (RuleCall)cNameAssignment_14.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Group cGroup_16 = (Group)cGroup.eContents().get(16);
		private final Keyword cCommaKeyword_16_0 = (Keyword)cGroup_16.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_16_1 = (Keyword)cGroup_16.eContents().get(1);
		private final Keyword cNamespaceKeyword_16_2 = (Keyword)cGroup_16.eContents().get(2);
		private final Keyword cQuotationMarkKeyword_16_3 = (Keyword)cGroup_16.eContents().get(3);
		private final Keyword cColonKeyword_16_4 = (Keyword)cGroup_16.eContents().get(4);
		private final Keyword cQuotationMarkKeyword_16_5 = (Keyword)cGroup_16.eContents().get(5);
		private final Assignment cNamespaceAssignment_16_6 = (Assignment)cGroup_16.eContents().get(6);
		private final RuleCall cNamespaceNamespaceParserRuleCall_16_6_0 = (RuleCall)cNamespaceAssignment_16_6.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_16_7 = (Keyword)cGroup_16.eContents().get(7);
		private final Keyword cCommaKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Keyword cQuotationMarkKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Keyword cFieldsKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Keyword cQuotationMarkKeyword_20 = (Keyword)cGroup.eContents().get(20);
		private final Keyword cColonKeyword_21 = (Keyword)cGroup.eContents().get(21);
		private final Keyword cLeftSquareBracketKeyword_22 = (Keyword)cGroup.eContents().get(22);
		private final Assignment cFieldListAssignment_23 = (Assignment)cGroup.eContents().get(23);
		private final RuleCall cFieldListFieldListParserRuleCall_23_0 = (RuleCall)cFieldListAssignment_23.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_24 = (Keyword)cGroup.eContents().get(24);
		private final Keyword cRightCurlyBracketKeyword_25 = (Keyword)cGroup.eContents().get(25);
		
		//RecordType returns Record:
		//	"{" "\"" "type" "\"" ":" "\"" "record" "\"" "," "\"" "name" "\"" ":" "\"" name=ID "\"" ("," "\"" "namespace" "\"" ":"
		//	"\"" namespace=Namespace "\"")? "," "\"" "fields" "\"" ":" "[" fieldList=FieldList "]" "}";
		public ParserRule getRule() { return rule; }

		//"{" "\"" "type" "\"" ":" "\"" "record" "\"" "," "\"" "name" "\"" ":" "\"" name=ID "\"" ("," "\"" "namespace" "\"" ":"
		//"\"" namespace=Namespace "\"")? "," "\"" "fields" "\"" ":" "[" fieldList=FieldList "]" "}"
		public Group getGroup() { return cGroup; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }

		//"\""
		public Keyword getQuotationMarkKeyword_1() { return cQuotationMarkKeyword_1; }

		//"type"
		public Keyword getTypeKeyword_2() { return cTypeKeyword_2; }

		//"\""
		public Keyword getQuotationMarkKeyword_3() { return cQuotationMarkKeyword_3; }

		//":"
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }

		//"\""
		public Keyword getQuotationMarkKeyword_5() { return cQuotationMarkKeyword_5; }

		//"record"
		public Keyword getRecordKeyword_6() { return cRecordKeyword_6; }

		//"\""
		public Keyword getQuotationMarkKeyword_7() { return cQuotationMarkKeyword_7; }

		//","
		public Keyword getCommaKeyword_8() { return cCommaKeyword_8; }

		//"\""
		public Keyword getQuotationMarkKeyword_9() { return cQuotationMarkKeyword_9; }

		//"name"
		public Keyword getNameKeyword_10() { return cNameKeyword_10; }

		//"\""
		public Keyword getQuotationMarkKeyword_11() { return cQuotationMarkKeyword_11; }

		//":"
		public Keyword getColonKeyword_12() { return cColonKeyword_12; }

		//"\""
		public Keyword getQuotationMarkKeyword_13() { return cQuotationMarkKeyword_13; }

		//name=ID
		public Assignment getNameAssignment_14() { return cNameAssignment_14; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_14_0() { return cNameIDTerminalRuleCall_14_0; }

		//"\""
		public Keyword getQuotationMarkKeyword_15() { return cQuotationMarkKeyword_15; }

		//("," "\"" "namespace" "\"" ":" "\"" namespace=Namespace "\"")?
		public Group getGroup_16() { return cGroup_16; }

		//","
		public Keyword getCommaKeyword_16_0() { return cCommaKeyword_16_0; }

		//"\""
		public Keyword getQuotationMarkKeyword_16_1() { return cQuotationMarkKeyword_16_1; }

		//"namespace"
		public Keyword getNamespaceKeyword_16_2() { return cNamespaceKeyword_16_2; }

		//"\""
		public Keyword getQuotationMarkKeyword_16_3() { return cQuotationMarkKeyword_16_3; }

		//":"
		public Keyword getColonKeyword_16_4() { return cColonKeyword_16_4; }

		//"\""
		public Keyword getQuotationMarkKeyword_16_5() { return cQuotationMarkKeyword_16_5; }

		//namespace=Namespace
		public Assignment getNamespaceAssignment_16_6() { return cNamespaceAssignment_16_6; }

		//Namespace
		public RuleCall getNamespaceNamespaceParserRuleCall_16_6_0() { return cNamespaceNamespaceParserRuleCall_16_6_0; }

		//"\""
		public Keyword getQuotationMarkKeyword_16_7() { return cQuotationMarkKeyword_16_7; }

		//","
		public Keyword getCommaKeyword_17() { return cCommaKeyword_17; }

		//"\""
		public Keyword getQuotationMarkKeyword_18() { return cQuotationMarkKeyword_18; }

		//"fields"
		public Keyword getFieldsKeyword_19() { return cFieldsKeyword_19; }

		//"\""
		public Keyword getQuotationMarkKeyword_20() { return cQuotationMarkKeyword_20; }

		//":"
		public Keyword getColonKeyword_21() { return cColonKeyword_21; }

		//"["
		public Keyword getLeftSquareBracketKeyword_22() { return cLeftSquareBracketKeyword_22; }

		//fieldList=FieldList
		public Assignment getFieldListAssignment_23() { return cFieldListAssignment_23; }

		//FieldList
		public RuleCall getFieldListFieldListParserRuleCall_23_0() { return cFieldListFieldListParserRuleCall_23_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_24() { return cRightSquareBracketKeyword_24; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_25() { return cRightCurlyBracketKeyword_25; }
	}

	public class FieldListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FieldList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cFieldsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cFieldsFieldParserRuleCall_0_0 = (RuleCall)cFieldsAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cFieldsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cFieldsFieldParserRuleCall_1_1_0 = (RuleCall)cFieldsAssignment_1_1.eContents().get(0);
		
		//FieldList:
		//	fields+=Field ("," fields+=Field)*;
		public ParserRule getRule() { return rule; }

		//fields+=Field ("," fields+=Field)*
		public Group getGroup() { return cGroup; }

		//fields+=Field
		public Assignment getFieldsAssignment_0() { return cFieldsAssignment_0; }

		//Field
		public RuleCall getFieldsFieldParserRuleCall_0_0() { return cFieldsFieldParserRuleCall_0_0; }

		//("," fields+=Field)*
		public Group getGroup_1() { return cGroup_1; }

		//","
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }

		//fields+=Field
		public Assignment getFieldsAssignment_1_1() { return cFieldsAssignment_1_1; }

		//Field
		public RuleCall getFieldsFieldParserRuleCall_1_1_0() { return cFieldsFieldParserRuleCall_1_1_0; }
	}

	public class FieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Field");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cQuotationMarkKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cQuotationMarkKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final Alternatives cNameAlternatives_6_0 = (Alternatives)cNameAssignment_6.eContents().get(0);
		private final Keyword cNameNameKeyword_6_0_0 = (Keyword)cNameAlternatives_6_0.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_6_0_1 = (RuleCall)cNameAlternatives_6_0.eContents().get(1);
		private final Keyword cQuotationMarkKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cQuotationMarkKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cTypeKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cQuotationMarkKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cColonKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Alternatives cAlternatives_13 = (Alternatives)cGroup.eContents().get(13);
		private final Assignment cPrimitiveAssignment_13_0 = (Assignment)cAlternatives_13.eContents().get(0);
		private final RuleCall cPrimitivePrimitiveParserRuleCall_13_0_0 = (RuleCall)cPrimitiveAssignment_13_0.eContents().get(0);
		private final Assignment cRecordAssignment_13_1 = (Assignment)cAlternatives_13.eContents().get(1);
		private final RuleCall cRecordRecordTypeParserRuleCall_13_1_0 = (RuleCall)cRecordAssignment_13_1.eContents().get(0);
		private final Group cGroup_13_2 = (Group)cAlternatives_13.eContents().get(2);
		private final Keyword cQuotationMarkKeyword_13_2_0 = (Keyword)cGroup_13_2.eContents().get(0);
		private final Assignment cRecordRefAssignment_13_2_1 = (Assignment)cGroup_13_2.eContents().get(1);
		private final CrossReference cRecordRefRecordCrossReference_13_2_1_0 = (CrossReference)cRecordRefAssignment_13_2_1.eContents().get(0);
		private final RuleCall cRecordRefRecordIDTerminalRuleCall_13_2_1_0_1 = (RuleCall)cRecordRefRecordCrossReference_13_2_1_0.eContents().get(1);
		private final Keyword cQuotationMarkKeyword_13_2_2 = (Keyword)cGroup_13_2.eContents().get(2);
		private final Assignment cEtypeAssignment_13_3 = (Assignment)cAlternatives_13.eContents().get(3);
		private final RuleCall cEtypeEnumTypeParserRuleCall_13_3_0 = (RuleCall)cEtypeAssignment_13_3.eContents().get(0);
		private final Assignment cArrayAssignment_13_4 = (Assignment)cAlternatives_13.eContents().get(4);
		private final RuleCall cArrayArrayTypeParserRuleCall_13_4_0 = (RuleCall)cArrayAssignment_13_4.eContents().get(0);
		private final Assignment cMapAssignment_13_5 = (Assignment)cAlternatives_13.eContents().get(5);
		private final RuleCall cMapMapTypeParserRuleCall_13_5_0 = (RuleCall)cMapAssignment_13_5.eContents().get(0);
		private final Assignment cFixedAssignment_13_6 = (Assignment)cAlternatives_13.eContents().get(6);
		private final RuleCall cFixedFixedTypeParserRuleCall_13_6_0 = (RuleCall)cFixedAssignment_13_6.eContents().get(0);
		private final Assignment cUnionAssignment_13_7 = (Assignment)cAlternatives_13.eContents().get(7);
		private final RuleCall cUnionUnionTypeParserRuleCall_13_7_0 = (RuleCall)cUnionAssignment_13_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//Field:
		//	"{" "\"" "name" "\"" ":" "\"" name=("name" | ID) "\"" "," "\"" "type" "\"" ":" (primitive=Primitive |
		//	record=RecordType | "\"" recordRef=[Record] "\"" | etype=EnumType | array=ArrayType | map=MapType | fixed=FixedType |
		//	union=UnionType) "}";
		public ParserRule getRule() { return rule; }

		//"{" "\"" "name" "\"" ":" "\"" name=("name" | ID) "\"" "," "\"" "type" "\"" ":" (primitive=Primitive | record=RecordType
		//| "\"" recordRef=[Record] "\"" | etype=EnumType | array=ArrayType | map=MapType | fixed=FixedType | union=UnionType)
		//"}"
		public Group getGroup() { return cGroup; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }

		//"\""
		public Keyword getQuotationMarkKeyword_1() { return cQuotationMarkKeyword_1; }

		//"name"
		public Keyword getNameKeyword_2() { return cNameKeyword_2; }

		//"\""
		public Keyword getQuotationMarkKeyword_3() { return cQuotationMarkKeyword_3; }

		//":"
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }

		//"\""
		public Keyword getQuotationMarkKeyword_5() { return cQuotationMarkKeyword_5; }

		//name=("name" | ID)
		public Assignment getNameAssignment_6() { return cNameAssignment_6; }

		//"name" | ID
		public Alternatives getNameAlternatives_6_0() { return cNameAlternatives_6_0; }

		//"name"
		public Keyword getNameNameKeyword_6_0_0() { return cNameNameKeyword_6_0_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_6_0_1() { return cNameIDTerminalRuleCall_6_0_1; }

		//"\""
		public Keyword getQuotationMarkKeyword_7() { return cQuotationMarkKeyword_7; }

		//","
		public Keyword getCommaKeyword_8() { return cCommaKeyword_8; }

		//"\""
		public Keyword getQuotationMarkKeyword_9() { return cQuotationMarkKeyword_9; }

		//"type"
		public Keyword getTypeKeyword_10() { return cTypeKeyword_10; }

		//"\""
		public Keyword getQuotationMarkKeyword_11() { return cQuotationMarkKeyword_11; }

		//":"
		public Keyword getColonKeyword_12() { return cColonKeyword_12; }

		//primitive=Primitive | record=RecordType | "\"" recordRef=[Record] "\"" | etype=EnumType | array=ArrayType | map=MapType
		//| fixed=FixedType | union=UnionType
		public Alternatives getAlternatives_13() { return cAlternatives_13; }

		//primitive=Primitive
		public Assignment getPrimitiveAssignment_13_0() { return cPrimitiveAssignment_13_0; }

		//Primitive
		public RuleCall getPrimitivePrimitiveParserRuleCall_13_0_0() { return cPrimitivePrimitiveParserRuleCall_13_0_0; }

		//record=RecordType
		public Assignment getRecordAssignment_13_1() { return cRecordAssignment_13_1; }

		//RecordType
		public RuleCall getRecordRecordTypeParserRuleCall_13_1_0() { return cRecordRecordTypeParserRuleCall_13_1_0; }

		//"\"" recordRef=[Record] "\""
		public Group getGroup_13_2() { return cGroup_13_2; }

		//"\""
		public Keyword getQuotationMarkKeyword_13_2_0() { return cQuotationMarkKeyword_13_2_0; }

		//recordRef=[Record]
		public Assignment getRecordRefAssignment_13_2_1() { return cRecordRefAssignment_13_2_1; }

		//[Record]
		public CrossReference getRecordRefRecordCrossReference_13_2_1_0() { return cRecordRefRecordCrossReference_13_2_1_0; }

		//ID
		public RuleCall getRecordRefRecordIDTerminalRuleCall_13_2_1_0_1() { return cRecordRefRecordIDTerminalRuleCall_13_2_1_0_1; }

		//"\""
		public Keyword getQuotationMarkKeyword_13_2_2() { return cQuotationMarkKeyword_13_2_2; }

		//etype=EnumType
		public Assignment getEtypeAssignment_13_3() { return cEtypeAssignment_13_3; }

		//EnumType
		public RuleCall getEtypeEnumTypeParserRuleCall_13_3_0() { return cEtypeEnumTypeParserRuleCall_13_3_0; }

		//array=ArrayType
		public Assignment getArrayAssignment_13_4() { return cArrayAssignment_13_4; }

		//ArrayType
		public RuleCall getArrayArrayTypeParserRuleCall_13_4_0() { return cArrayArrayTypeParserRuleCall_13_4_0; }

		//map=MapType
		public Assignment getMapAssignment_13_5() { return cMapAssignment_13_5; }

		//MapType
		public RuleCall getMapMapTypeParserRuleCall_13_5_0() { return cMapMapTypeParserRuleCall_13_5_0; }

		//fixed=FixedType
		public Assignment getFixedAssignment_13_6() { return cFixedAssignment_13_6; }

		//FixedType
		public RuleCall getFixedFixedTypeParserRuleCall_13_6_0() { return cFixedFixedTypeParserRuleCall_13_6_0; }

		//union=UnionType
		public Assignment getUnionAssignment_13_7() { return cUnionAssignment_13_7; }

		//UnionType
		public RuleCall getUnionUnionTypeParserRuleCall_13_7_0() { return cUnionUnionTypeParserRuleCall_13_7_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}

	public class EnumTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EnumType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cQuotationMarkKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cQuotationMarkKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cEnumKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cQuotationMarkKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cQuotationMarkKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cNameKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cQuotationMarkKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cColonKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cQuotationMarkKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cNameAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cNameIDTerminalRuleCall_14_0 = (RuleCall)cNameAssignment_14.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cCommaKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Keyword cQuotationMarkKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Keyword cSymbolsKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Keyword cQuotationMarkKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Keyword cColonKeyword_20 = (Keyword)cGroup.eContents().get(20);
		private final Keyword cLeftSquareBracketKeyword_21 = (Keyword)cGroup.eContents().get(21);
		private final Group cGroup_22 = (Group)cGroup.eContents().get(22);
		private final Keyword cQuotationMarkKeyword_22_0 = (Keyword)cGroup_22.eContents().get(0);
		private final Assignment cSymbolsAssignment_22_1 = (Assignment)cGroup_22.eContents().get(1);
		private final RuleCall cSymbolsIDTerminalRuleCall_22_1_0 = (RuleCall)cSymbolsAssignment_22_1.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_22_2 = (Keyword)cGroup_22.eContents().get(2);
		private final Group cGroup_23 = (Group)cGroup.eContents().get(23);
		private final Keyword cCommaKeyword_23_0 = (Keyword)cGroup_23.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_23_1 = (Keyword)cGroup_23.eContents().get(1);
		private final Assignment cSymbolsAssignment_23_2 = (Assignment)cGroup_23.eContents().get(2);
		private final RuleCall cSymbolsIDTerminalRuleCall_23_2_0 = (RuleCall)cSymbolsAssignment_23_2.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_23_3 = (Keyword)cGroup_23.eContents().get(3);
		private final Keyword cRightSquareBracketKeyword_24 = (Keyword)cGroup.eContents().get(24);
		private final Keyword cRightCurlyBracketKeyword_25 = (Keyword)cGroup.eContents().get(25);
		
		//EnumType:
		//	"{" "\"" "type" "\"" ":" "\"" "enum" "\"" "," "\"" "name" "\"" ":" "\"" name=ID "\"" "," "\"" "symbols" "\"" ":" "["
		//	("\"" symbols+=ID "\"") ("," "\"" symbols+=ID "\"")* "]" "}";
		public ParserRule getRule() { return rule; }

		//"{" "\"" "type" "\"" ":" "\"" "enum" "\"" "," "\"" "name" "\"" ":" "\"" name=ID "\"" "," "\"" "symbols" "\"" ":" "["
		//("\"" symbols+=ID "\"") ("," "\"" symbols+=ID "\"")* "]" "}"
		public Group getGroup() { return cGroup; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }

		//"\""
		public Keyword getQuotationMarkKeyword_1() { return cQuotationMarkKeyword_1; }

		//"type"
		public Keyword getTypeKeyword_2() { return cTypeKeyword_2; }

		//"\""
		public Keyword getQuotationMarkKeyword_3() { return cQuotationMarkKeyword_3; }

		//":"
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }

		//"\""
		public Keyword getQuotationMarkKeyword_5() { return cQuotationMarkKeyword_5; }

		//"enum"
		public Keyword getEnumKeyword_6() { return cEnumKeyword_6; }

		//"\""
		public Keyword getQuotationMarkKeyword_7() { return cQuotationMarkKeyword_7; }

		//","
		public Keyword getCommaKeyword_8() { return cCommaKeyword_8; }

		//"\""
		public Keyword getQuotationMarkKeyword_9() { return cQuotationMarkKeyword_9; }

		//"name"
		public Keyword getNameKeyword_10() { return cNameKeyword_10; }

		//"\""
		public Keyword getQuotationMarkKeyword_11() { return cQuotationMarkKeyword_11; }

		//":"
		public Keyword getColonKeyword_12() { return cColonKeyword_12; }

		//"\""
		public Keyword getQuotationMarkKeyword_13() { return cQuotationMarkKeyword_13; }

		//name=ID
		public Assignment getNameAssignment_14() { return cNameAssignment_14; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_14_0() { return cNameIDTerminalRuleCall_14_0; }

		//"\""
		public Keyword getQuotationMarkKeyword_15() { return cQuotationMarkKeyword_15; }

		//","
		public Keyword getCommaKeyword_16() { return cCommaKeyword_16; }

		//"\""
		public Keyword getQuotationMarkKeyword_17() { return cQuotationMarkKeyword_17; }

		//"symbols"
		public Keyword getSymbolsKeyword_18() { return cSymbolsKeyword_18; }

		//"\""
		public Keyword getQuotationMarkKeyword_19() { return cQuotationMarkKeyword_19; }

		//":"
		public Keyword getColonKeyword_20() { return cColonKeyword_20; }

		//"["
		public Keyword getLeftSquareBracketKeyword_21() { return cLeftSquareBracketKeyword_21; }

		//"\"" symbols+=ID "\""
		public Group getGroup_22() { return cGroup_22; }

		//"\""
		public Keyword getQuotationMarkKeyword_22_0() { return cQuotationMarkKeyword_22_0; }

		//symbols+=ID
		public Assignment getSymbolsAssignment_22_1() { return cSymbolsAssignment_22_1; }

		//ID
		public RuleCall getSymbolsIDTerminalRuleCall_22_1_0() { return cSymbolsIDTerminalRuleCall_22_1_0; }

		//"\""
		public Keyword getQuotationMarkKeyword_22_2() { return cQuotationMarkKeyword_22_2; }

		//("," "\"" symbols+=ID "\"")*
		public Group getGroup_23() { return cGroup_23; }

		//","
		public Keyword getCommaKeyword_23_0() { return cCommaKeyword_23_0; }

		//"\""
		public Keyword getQuotationMarkKeyword_23_1() { return cQuotationMarkKeyword_23_1; }

		//symbols+=ID
		public Assignment getSymbolsAssignment_23_2() { return cSymbolsAssignment_23_2; }

		//ID
		public RuleCall getSymbolsIDTerminalRuleCall_23_2_0() { return cSymbolsIDTerminalRuleCall_23_2_0; }

		//"\""
		public Keyword getQuotationMarkKeyword_23_3() { return cQuotationMarkKeyword_23_3; }

		//"]"
		public Keyword getRightSquareBracketKeyword_24() { return cRightSquareBracketKeyword_24; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_25() { return cRightCurlyBracketKeyword_25; }
	}

	public class ArrayTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ArrayType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cQuotationMarkKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cQuotationMarkKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cArrayKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cQuotationMarkKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cQuotationMarkKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cItemsKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cQuotationMarkKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cColonKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Alternatives cAlternatives_13 = (Alternatives)cGroup.eContents().get(13);
		private final Assignment cPrimitiveAssignment_13_0 = (Assignment)cAlternatives_13.eContents().get(0);
		private final RuleCall cPrimitivePrimitiveParserRuleCall_13_0_0 = (RuleCall)cPrimitiveAssignment_13_0.eContents().get(0);
		private final Assignment cRecordAssignment_13_1 = (Assignment)cAlternatives_13.eContents().get(1);
		private final RuleCall cRecordRecordTypeParserRuleCall_13_1_0 = (RuleCall)cRecordAssignment_13_1.eContents().get(0);
		private final Group cGroup_13_2 = (Group)cAlternatives_13.eContents().get(2);
		private final Keyword cQuotationMarkKeyword_13_2_0 = (Keyword)cGroup_13_2.eContents().get(0);
		private final Assignment cRecordRefAssignment_13_2_1 = (Assignment)cGroup_13_2.eContents().get(1);
		private final CrossReference cRecordRefRecordCrossReference_13_2_1_0 = (CrossReference)cRecordRefAssignment_13_2_1.eContents().get(0);
		private final RuleCall cRecordRefRecordIDTerminalRuleCall_13_2_1_0_1 = (RuleCall)cRecordRefRecordCrossReference_13_2_1_0.eContents().get(1);
		private final Keyword cQuotationMarkKeyword_13_2_2 = (Keyword)cGroup_13_2.eContents().get(2);
		private final Assignment cEtypeAssignment_13_3 = (Assignment)cAlternatives_13.eContents().get(3);
		private final RuleCall cEtypeEnumTypeParserRuleCall_13_3_0 = (RuleCall)cEtypeAssignment_13_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//ArrayType:
		//	"{" "\"" "type" "\"" ":" "\"" "array" "\"" "," "\"" "items" "\"" ":" (primitive=Primitive | record=RecordType | "\""
		//	recordRef=[Record] "\"" | etype=EnumType) "}";
		public ParserRule getRule() { return rule; }

		//"{" "\"" "type" "\"" ":" "\"" "array" "\"" "," "\"" "items" "\"" ":" (primitive=Primitive | record=RecordType | "\""
		//recordRef=[Record] "\"" | etype=EnumType) "}"
		public Group getGroup() { return cGroup; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }

		//"\""
		public Keyword getQuotationMarkKeyword_1() { return cQuotationMarkKeyword_1; }

		//"type"
		public Keyword getTypeKeyword_2() { return cTypeKeyword_2; }

		//"\""
		public Keyword getQuotationMarkKeyword_3() { return cQuotationMarkKeyword_3; }

		//":"
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }

		//"\""
		public Keyword getQuotationMarkKeyword_5() { return cQuotationMarkKeyword_5; }

		//"array"
		public Keyword getArrayKeyword_6() { return cArrayKeyword_6; }

		//"\""
		public Keyword getQuotationMarkKeyword_7() { return cQuotationMarkKeyword_7; }

		//","
		public Keyword getCommaKeyword_8() { return cCommaKeyword_8; }

		//"\""
		public Keyword getQuotationMarkKeyword_9() { return cQuotationMarkKeyword_9; }

		//"items"
		public Keyword getItemsKeyword_10() { return cItemsKeyword_10; }

		//"\""
		public Keyword getQuotationMarkKeyword_11() { return cQuotationMarkKeyword_11; }

		//":"
		public Keyword getColonKeyword_12() { return cColonKeyword_12; }

		//primitive=Primitive | record=RecordType | "\"" recordRef=[Record] "\"" | etype=EnumType
		public Alternatives getAlternatives_13() { return cAlternatives_13; }

		//primitive=Primitive
		public Assignment getPrimitiveAssignment_13_0() { return cPrimitiveAssignment_13_0; }

		//Primitive
		public RuleCall getPrimitivePrimitiveParserRuleCall_13_0_0() { return cPrimitivePrimitiveParserRuleCall_13_0_0; }

		//record=RecordType
		public Assignment getRecordAssignment_13_1() { return cRecordAssignment_13_1; }

		//RecordType
		public RuleCall getRecordRecordTypeParserRuleCall_13_1_0() { return cRecordRecordTypeParserRuleCall_13_1_0; }

		//"\"" recordRef=[Record] "\""
		public Group getGroup_13_2() { return cGroup_13_2; }

		//"\""
		public Keyword getQuotationMarkKeyword_13_2_0() { return cQuotationMarkKeyword_13_2_0; }

		//recordRef=[Record]
		public Assignment getRecordRefAssignment_13_2_1() { return cRecordRefAssignment_13_2_1; }

		//[Record]
		public CrossReference getRecordRefRecordCrossReference_13_2_1_0() { return cRecordRefRecordCrossReference_13_2_1_0; }

		//ID
		public RuleCall getRecordRefRecordIDTerminalRuleCall_13_2_1_0_1() { return cRecordRefRecordIDTerminalRuleCall_13_2_1_0_1; }

		//"\""
		public Keyword getQuotationMarkKeyword_13_2_2() { return cQuotationMarkKeyword_13_2_2; }

		//etype=EnumType
		public Assignment getEtypeAssignment_13_3() { return cEtypeAssignment_13_3; }

		//EnumType
		public RuleCall getEtypeEnumTypeParserRuleCall_13_3_0() { return cEtypeEnumTypeParserRuleCall_13_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}

	public class MapTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MapType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cQuotationMarkKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cQuotationMarkKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cMapKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cQuotationMarkKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cQuotationMarkKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cItemsKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cQuotationMarkKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cColonKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Alternatives cAlternatives_13 = (Alternatives)cGroup.eContents().get(13);
		private final Assignment cPrimitiveAssignment_13_0 = (Assignment)cAlternatives_13.eContents().get(0);
		private final RuleCall cPrimitivePrimitiveParserRuleCall_13_0_0 = (RuleCall)cPrimitiveAssignment_13_0.eContents().get(0);
		private final Assignment cRecordAssignment_13_1 = (Assignment)cAlternatives_13.eContents().get(1);
		private final RuleCall cRecordRecordTypeParserRuleCall_13_1_0 = (RuleCall)cRecordAssignment_13_1.eContents().get(0);
		private final Group cGroup_13_2 = (Group)cAlternatives_13.eContents().get(2);
		private final Keyword cQuotationMarkKeyword_13_2_0 = (Keyword)cGroup_13_2.eContents().get(0);
		private final Assignment cRecordRefAssignment_13_2_1 = (Assignment)cGroup_13_2.eContents().get(1);
		private final CrossReference cRecordRefRecordCrossReference_13_2_1_0 = (CrossReference)cRecordRefAssignment_13_2_1.eContents().get(0);
		private final RuleCall cRecordRefRecordIDTerminalRuleCall_13_2_1_0_1 = (RuleCall)cRecordRefRecordCrossReference_13_2_1_0.eContents().get(1);
		private final Keyword cQuotationMarkKeyword_13_2_2 = (Keyword)cGroup_13_2.eContents().get(2);
		private final Assignment cEtypeAssignment_13_3 = (Assignment)cAlternatives_13.eContents().get(3);
		private final RuleCall cEtypeEnumTypeParserRuleCall_13_3_0 = (RuleCall)cEtypeAssignment_13_3.eContents().get(0);
		private final Assignment cAtypeAssignment_13_4 = (Assignment)cAlternatives_13.eContents().get(4);
		private final RuleCall cAtypeArrayTypeParserRuleCall_13_4_0 = (RuleCall)cAtypeAssignment_13_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//MapType:
		//	"{" "\"" "type" "\"" ":" "\"" "map" "\"" "," "\"" "items" "\"" ":" (primitive=Primitive | record=RecordType | "\""
		//	recordRef=[Record] "\"" | etype=EnumType | atype=ArrayType) "}";
		public ParserRule getRule() { return rule; }

		//"{" "\"" "type" "\"" ":" "\"" "map" "\"" "," "\"" "items" "\"" ":" (primitive=Primitive | record=RecordType | "\""
		//recordRef=[Record] "\"" | etype=EnumType | atype=ArrayType) "}"
		public Group getGroup() { return cGroup; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }

		//"\""
		public Keyword getQuotationMarkKeyword_1() { return cQuotationMarkKeyword_1; }

		//"type"
		public Keyword getTypeKeyword_2() { return cTypeKeyword_2; }

		//"\""
		public Keyword getQuotationMarkKeyword_3() { return cQuotationMarkKeyword_3; }

		//":"
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }

		//"\""
		public Keyword getQuotationMarkKeyword_5() { return cQuotationMarkKeyword_5; }

		//"map"
		public Keyword getMapKeyword_6() { return cMapKeyword_6; }

		//"\""
		public Keyword getQuotationMarkKeyword_7() { return cQuotationMarkKeyword_7; }

		//","
		public Keyword getCommaKeyword_8() { return cCommaKeyword_8; }

		//"\""
		public Keyword getQuotationMarkKeyword_9() { return cQuotationMarkKeyword_9; }

		//"items"
		public Keyword getItemsKeyword_10() { return cItemsKeyword_10; }

		//"\""
		public Keyword getQuotationMarkKeyword_11() { return cQuotationMarkKeyword_11; }

		//":"
		public Keyword getColonKeyword_12() { return cColonKeyword_12; }

		//primitive=Primitive | record=RecordType | "\"" recordRef=[Record] "\"" | etype=EnumType | atype=ArrayType
		public Alternatives getAlternatives_13() { return cAlternatives_13; }

		//primitive=Primitive
		public Assignment getPrimitiveAssignment_13_0() { return cPrimitiveAssignment_13_0; }

		//Primitive
		public RuleCall getPrimitivePrimitiveParserRuleCall_13_0_0() { return cPrimitivePrimitiveParserRuleCall_13_0_0; }

		//record=RecordType
		public Assignment getRecordAssignment_13_1() { return cRecordAssignment_13_1; }

		//RecordType
		public RuleCall getRecordRecordTypeParserRuleCall_13_1_0() { return cRecordRecordTypeParserRuleCall_13_1_0; }

		//"\"" recordRef=[Record] "\""
		public Group getGroup_13_2() { return cGroup_13_2; }

		//"\""
		public Keyword getQuotationMarkKeyword_13_2_0() { return cQuotationMarkKeyword_13_2_0; }

		//recordRef=[Record]
		public Assignment getRecordRefAssignment_13_2_1() { return cRecordRefAssignment_13_2_1; }

		//[Record]
		public CrossReference getRecordRefRecordCrossReference_13_2_1_0() { return cRecordRefRecordCrossReference_13_2_1_0; }

		//ID
		public RuleCall getRecordRefRecordIDTerminalRuleCall_13_2_1_0_1() { return cRecordRefRecordIDTerminalRuleCall_13_2_1_0_1; }

		//"\""
		public Keyword getQuotationMarkKeyword_13_2_2() { return cQuotationMarkKeyword_13_2_2; }

		//etype=EnumType
		public Assignment getEtypeAssignment_13_3() { return cEtypeAssignment_13_3; }

		//EnumType
		public RuleCall getEtypeEnumTypeParserRuleCall_13_3_0() { return cEtypeEnumTypeParserRuleCall_13_3_0; }

		//atype=ArrayType
		public Assignment getAtypeAssignment_13_4() { return cAtypeAssignment_13_4; }

		//ArrayType
		public RuleCall getAtypeArrayTypeParserRuleCall_13_4_0() { return cAtypeArrayTypeParserRuleCall_13_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}

	public class FixedTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FixedType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cQuotationMarkKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cFixedKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cQuotationMarkKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cQuotationMarkKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cNameKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cQuotationMarkKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cColonKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cQuotationMarkKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cNameAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cNameIDTerminalRuleCall_9_0 = (RuleCall)cNameAssignment_9.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cCommaKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cQuotationMarkKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cSizeKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cQuotationMarkKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cColonKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cQuotationMarkKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cSizeAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cSizeINTTerminalRuleCall_17_0 = (RuleCall)cSizeAssignment_17.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_18 = (Keyword)cGroup.eContents().get(18);
		
		//FixedType:
		//	"\"" "fixed" "\"" "," "\"" "name" "\"" ":" "\"" name=ID "\"" "," "\"" "size" "\"" ":" "\"" size=INT "\"";
		public ParserRule getRule() { return rule; }

		//"\"" "fixed" "\"" "," "\"" "name" "\"" ":" "\"" name=ID "\"" "," "\"" "size" "\"" ":" "\"" size=INT "\""
		public Group getGroup() { return cGroup; }

		//"\""
		public Keyword getQuotationMarkKeyword_0() { return cQuotationMarkKeyword_0; }

		//"fixed"
		public Keyword getFixedKeyword_1() { return cFixedKeyword_1; }

		//"\""
		public Keyword getQuotationMarkKeyword_2() { return cQuotationMarkKeyword_2; }

		//","
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }

		//"\""
		public Keyword getQuotationMarkKeyword_4() { return cQuotationMarkKeyword_4; }

		//"name"
		public Keyword getNameKeyword_5() { return cNameKeyword_5; }

		//"\""
		public Keyword getQuotationMarkKeyword_6() { return cQuotationMarkKeyword_6; }

		//":"
		public Keyword getColonKeyword_7() { return cColonKeyword_7; }

		//"\""
		public Keyword getQuotationMarkKeyword_8() { return cQuotationMarkKeyword_8; }

		//name=ID
		public Assignment getNameAssignment_9() { return cNameAssignment_9; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_9_0() { return cNameIDTerminalRuleCall_9_0; }

		//"\""
		public Keyword getQuotationMarkKeyword_10() { return cQuotationMarkKeyword_10; }

		//","
		public Keyword getCommaKeyword_11() { return cCommaKeyword_11; }

		//"\""
		public Keyword getQuotationMarkKeyword_12() { return cQuotationMarkKeyword_12; }

		//"size"
		public Keyword getSizeKeyword_13() { return cSizeKeyword_13; }

		//"\""
		public Keyword getQuotationMarkKeyword_14() { return cQuotationMarkKeyword_14; }

		//":"
		public Keyword getColonKeyword_15() { return cColonKeyword_15; }

		//"\""
		public Keyword getQuotationMarkKeyword_16() { return cQuotationMarkKeyword_16; }

		//size=INT
		public Assignment getSizeAssignment_17() { return cSizeAssignment_17; }

		//INT
		public RuleCall getSizeINTTerminalRuleCall_17_0() { return cSizeINTTerminalRuleCall_17_0; }

		//"\""
		public Keyword getQuotationMarkKeyword_18() { return cQuotationMarkKeyword_18; }
	}

	public class PrimitiveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Primitive");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cQuotationMarkKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cTypeAlternatives_1_0 = (Alternatives)cTypeAssignment_1.eContents().get(0);
		private final Keyword cTypeNullKeyword_1_0_0 = (Keyword)cTypeAlternatives_1_0.eContents().get(0);
		private final Keyword cTypeBooleanKeyword_1_0_1 = (Keyword)cTypeAlternatives_1_0.eContents().get(1);
		private final Keyword cTypeIntKeyword_1_0_2 = (Keyword)cTypeAlternatives_1_0.eContents().get(2);
		private final Keyword cTypeLongKeyword_1_0_3 = (Keyword)cTypeAlternatives_1_0.eContents().get(3);
		private final Keyword cTypeFloatKeyword_1_0_4 = (Keyword)cTypeAlternatives_1_0.eContents().get(4);
		private final Keyword cTypeDoubleKeyword_1_0_5 = (Keyword)cTypeAlternatives_1_0.eContents().get(5);
		private final Keyword cTypeBytesKeyword_1_0_6 = (Keyword)cTypeAlternatives_1_0.eContents().get(6);
		private final Keyword cTypeStringKeyword_1_0_7 = (Keyword)cTypeAlternatives_1_0.eContents().get(7);
		private final Keyword cQuotationMarkKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Primitive:
		//	"\"" type=("null" | "boolean" | "int" | "long" | "float" | "double" | "bytes" | "string") "\"";
		public ParserRule getRule() { return rule; }

		//"\"" type=("null" | "boolean" | "int" | "long" | "float" | "double" | "bytes" | "string") "\""
		public Group getGroup() { return cGroup; }

		//"\""
		public Keyword getQuotationMarkKeyword_0() { return cQuotationMarkKeyword_0; }

		//type=("null" | "boolean" | "int" | "long" | "float" | "double" | "bytes" | "string")
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }

		//"null" | "boolean" | "int" | "long" | "float" | "double" | "bytes" | "string"
		public Alternatives getTypeAlternatives_1_0() { return cTypeAlternatives_1_0; }

		//"null"
		public Keyword getTypeNullKeyword_1_0_0() { return cTypeNullKeyword_1_0_0; }

		//"boolean"
		public Keyword getTypeBooleanKeyword_1_0_1() { return cTypeBooleanKeyword_1_0_1; }

		//"int"
		public Keyword getTypeIntKeyword_1_0_2() { return cTypeIntKeyword_1_0_2; }

		//"long"
		public Keyword getTypeLongKeyword_1_0_3() { return cTypeLongKeyword_1_0_3; }

		//"float"
		public Keyword getTypeFloatKeyword_1_0_4() { return cTypeFloatKeyword_1_0_4; }

		//"double"
		public Keyword getTypeDoubleKeyword_1_0_5() { return cTypeDoubleKeyword_1_0_5; }

		//"bytes"
		public Keyword getTypeBytesKeyword_1_0_6() { return cTypeBytesKeyword_1_0_6; }

		//"string"
		public Keyword getTypeStringKeyword_1_0_7() { return cTypeStringKeyword_1_0_7; }

		//"\""
		public Keyword getQuotationMarkKeyword_2() { return cQuotationMarkKeyword_2; }
	}

	public class NamespaceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Namespace");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//Namespace:
		//	ID ("." ID)*;
		public ParserRule getRule() { return rule; }

		//ID ("." ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//("." ID)*
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	
	
	private final AvroSchemaElements pAvroSchema;
	private final UnionTypeElements pUnionType;
	private final UnionMemberElements pUnionMember;
	private final JsonTypeElements pJsonType;
	private final RecordTypeElements pRecordType;
	private final FieldListElements pFieldList;
	private final FieldElements pField;
	private final EnumTypeElements pEnumType;
	private final ArrayTypeElements pArrayType;
	private final MapTypeElements pMapType;
	private final FixedTypeElements pFixedType;
	private final PrimitiveElements pPrimitive;
	private final NamespaceElements pNamespace;
	private final TerminalRule tID;
	private final TerminalRule tINT;
	private final TerminalRule tML_COMMENT;
	private final TerminalRule tSL_COMMENT;
	private final TerminalRule tWS;
	private final TerminalRule tANY_OTHER;
	
	private final Grammar grammar;

	@Inject
	public AvroSchemaGrammarAccess(GrammarProvider grammarProvider) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.pAvroSchema = new AvroSchemaElements();
		this.pUnionType = new UnionTypeElements();
		this.pUnionMember = new UnionMemberElements();
		this.pJsonType = new JsonTypeElements();
		this.pRecordType = new RecordTypeElements();
		this.pFieldList = new FieldListElements();
		this.pField = new FieldElements();
		this.pEnumType = new EnumTypeElements();
		this.pArrayType = new ArrayTypeElements();
		this.pMapType = new MapTypeElements();
		this.pFixedType = new FixedTypeElements();
		this.pPrimitive = new PrimitiveElements();
		this.pNamespace = new NamespaceElements();
		this.tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ID");
		this.tINT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "INT");
		this.tML_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ML_COMMENT");
		this.tSL_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SL_COMMENT");
		this.tWS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "WS");
		this.tANY_OTHER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ANY_OTHER");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("net.langleystudios.dsl.AvroSchema".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	
	//AvroSchema:
	//	types+=(JsonType | RecordType | UnionType);
	public AvroSchemaElements getAvroSchemaAccess() {
		return pAvroSchema;
	}
	
	public ParserRule getAvroSchemaRule() {
		return getAvroSchemaAccess().getRule();
	}

	//UnionType:
	//	"[" types+=UnionMember ("," types+=UnionMember)* "]";
	public UnionTypeElements getUnionTypeAccess() {
		return pUnionType;
	}
	
	public ParserRule getUnionTypeRule() {
		return getUnionTypeAccess().getRule();
	}

	//UnionMember:
	//	RecordType | ArrayType | Primitive | MapType | EnumType | FixedType | "\"" recordRef=[Record] "\"";
	public UnionMemberElements getUnionMemberAccess() {
		return pUnionMember;
	}
	
	public ParserRule getUnionMemberRule() {
		return getUnionMemberAccess().getRule();
	}

	//JsonType:
	//	"{" "\"" "type" "\"" ":" "\"" type=Primitive "\"" "}";
	public JsonTypeElements getJsonTypeAccess() {
		return pJsonType;
	}
	
	public ParserRule getJsonTypeRule() {
		return getJsonTypeAccess().getRule();
	}

	//RecordType returns Record:
	//	"{" "\"" "type" "\"" ":" "\"" "record" "\"" "," "\"" "name" "\"" ":" "\"" name=ID "\"" ("," "\"" "namespace" "\"" ":"
	//	"\"" namespace=Namespace "\"")? "," "\"" "fields" "\"" ":" "[" fieldList=FieldList "]" "}";
	public RecordTypeElements getRecordTypeAccess() {
		return pRecordType;
	}
	
	public ParserRule getRecordTypeRule() {
		return getRecordTypeAccess().getRule();
	}

	//FieldList:
	//	fields+=Field ("," fields+=Field)*;
	public FieldListElements getFieldListAccess() {
		return pFieldList;
	}
	
	public ParserRule getFieldListRule() {
		return getFieldListAccess().getRule();
	}

	//Field:
	//	"{" "\"" "name" "\"" ":" "\"" name=("name" | ID) "\"" "," "\"" "type" "\"" ":" (primitive=Primitive |
	//	record=RecordType | "\"" recordRef=[Record] "\"" | etype=EnumType | array=ArrayType | map=MapType | fixed=FixedType |
	//	union=UnionType) "}";
	public FieldElements getFieldAccess() {
		return pField;
	}
	
	public ParserRule getFieldRule() {
		return getFieldAccess().getRule();
	}

	//EnumType:
	//	"{" "\"" "type" "\"" ":" "\"" "enum" "\"" "," "\"" "name" "\"" ":" "\"" name=ID "\"" "," "\"" "symbols" "\"" ":" "["
	//	("\"" symbols+=ID "\"") ("," "\"" symbols+=ID "\"")* "]" "}";
	public EnumTypeElements getEnumTypeAccess() {
		return pEnumType;
	}
	
	public ParserRule getEnumTypeRule() {
		return getEnumTypeAccess().getRule();
	}

	//ArrayType:
	//	"{" "\"" "type" "\"" ":" "\"" "array" "\"" "," "\"" "items" "\"" ":" (primitive=Primitive | record=RecordType | "\""
	//	recordRef=[Record] "\"" | etype=EnumType) "}";
	public ArrayTypeElements getArrayTypeAccess() {
		return pArrayType;
	}
	
	public ParserRule getArrayTypeRule() {
		return getArrayTypeAccess().getRule();
	}

	//MapType:
	//	"{" "\"" "type" "\"" ":" "\"" "map" "\"" "," "\"" "items" "\"" ":" (primitive=Primitive | record=RecordType | "\""
	//	recordRef=[Record] "\"" | etype=EnumType | atype=ArrayType) "}";
	public MapTypeElements getMapTypeAccess() {
		return pMapType;
	}
	
	public ParserRule getMapTypeRule() {
		return getMapTypeAccess().getRule();
	}

	//FixedType:
	//	"\"" "fixed" "\"" "," "\"" "name" "\"" ":" "\"" name=ID "\"" "," "\"" "size" "\"" ":" "\"" size=INT "\"";
	public FixedTypeElements getFixedTypeAccess() {
		return pFixedType;
	}
	
	public ParserRule getFixedTypeRule() {
		return getFixedTypeAccess().getRule();
	}

	//Primitive:
	//	"\"" type=("null" | "boolean" | "int" | "long" | "float" | "double" | "bytes" | "string") "\"";
	public PrimitiveElements getPrimitiveAccess() {
		return pPrimitive;
	}
	
	public ParserRule getPrimitiveRule() {
		return getPrimitiveAccess().getRule();
	}

	//Namespace:
	//	ID ("." ID)*;
	public NamespaceElements getNamespaceAccess() {
		return pNamespace;
	}
	
	public ParserRule getNamespaceRule() {
		return getNamespaceAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return tID;
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return tINT;
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return tML_COMMENT;
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return tSL_COMMENT;
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return tWS;
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return tANY_OTHER;
	} 
}
