/*
 * generated by Xtext
 */
package net.langleystudios.dsl.ui.contentassist

import net.langleystudios.dsl.ui.contentassist.AbstractAvroSchemaProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class AvroSchemaProposalProvider extends AbstractAvroSchemaProposalProvider {
}
