/*
 * generated by Xtext
 */
package net.langleystudios.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractAvroSchemaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(net.langleystudios.dsl.avroSchema.AvroSchemaPackage.eINSTANCE);
		return result;
	}
}
