/*
 * generated by Xtext
 */
package net.langleystudios.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import net.langleystudios.dsl.ui.internal.AvroSchemaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AvroSchemaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AvroSchemaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AvroSchemaActivator.getInstance().getInjector(AvroSchemaActivator.NET_LANGLEYSTUDIOS_DSL_AVROSCHEMA);
	}
	
}
