/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.eclipse.emf.examples.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum BookCategory { 
  Mystery, ScienceFiction, Biography  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"BookCategory\",\"namespace\":\"org.eclipse.emf.examples.avro\",\"symbols\":[\"Mystery\",\"ScienceFiction\",\"Biography\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
