/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.extlibrary;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Borrower extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Borrower\",\"namespace\":\"avro.extlibrary\",\"fields\":[{\"name\":\"address\",\"type\":\"string\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"borrowed\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Lendable\",\"fields\":[{\"name\":\"copies\",\"type\":\"int\"},{\"name\":\"borrowers\",\"type\":{\"type\":\"array\",\"items\":\"Borrower\"}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence address;
  @Deprecated public java.lang.CharSequence firstName;
  @Deprecated public java.lang.CharSequence lastName;
  @Deprecated public java.util.List<avro.extlibrary.Lendable> borrowed;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public Borrower() {}

  /**
   * All-args constructor.
   */
  public Borrower(java.lang.CharSequence address, java.lang.CharSequence firstName, java.lang.CharSequence lastName, java.util.List<avro.extlibrary.Lendable> borrowed) {
    this.address = address;
    this.firstName = firstName;
    this.lastName = lastName;
    this.borrowed = borrowed;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return address;
    case 1: return firstName;
    case 2: return lastName;
    case 3: return borrowed;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: address = (java.lang.CharSequence)value$; break;
    case 1: firstName = (java.lang.CharSequence)value$; break;
    case 2: lastName = (java.lang.CharSequence)value$; break;
    case 3: borrowed = (java.util.List<avro.extlibrary.Lendable>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'address' field.
   */
  public java.lang.CharSequence getAddress() {
    return address;
  }

  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(java.lang.CharSequence value) {
    this.address = value;
  }

  /**
   * Gets the value of the 'firstName' field.
   */
  public java.lang.CharSequence getFirstName() {
    return firstName;
  }

  /**
   * Sets the value of the 'firstName' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   */
  public java.lang.CharSequence getLastName() {
    return lastName;
  }

  /**
   * Sets the value of the 'lastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the 'borrowed' field.
   */
  public java.util.List<avro.extlibrary.Lendable> getBorrowed() {
    return borrowed;
  }

  /**
   * Sets the value of the 'borrowed' field.
   * @param value the value to set.
   */
  public void setBorrowed(java.util.List<avro.extlibrary.Lendable> value) {
    this.borrowed = value;
  }

  /** Creates a new Borrower RecordBuilder */
  public static avro.extlibrary.Borrower.Builder newBuilder() {
    return new avro.extlibrary.Borrower.Builder();
  }
  
  /** Creates a new Borrower RecordBuilder by copying an existing Builder */
  public static avro.extlibrary.Borrower.Builder newBuilder(avro.extlibrary.Borrower.Builder other) {
    return new avro.extlibrary.Borrower.Builder(other);
  }
  
  /** Creates a new Borrower RecordBuilder by copying an existing Borrower instance */
  public static avro.extlibrary.Borrower.Builder newBuilder(avro.extlibrary.Borrower other) {
    return new avro.extlibrary.Borrower.Builder(other);
  }
  
  /**
   * RecordBuilder for Borrower instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Borrower>
    implements org.apache.avro.data.RecordBuilder<Borrower> {

    private java.lang.CharSequence address;
    private java.lang.CharSequence firstName;
    private java.lang.CharSequence lastName;
    private java.util.List<avro.extlibrary.Lendable> borrowed;

    /** Creates a new Builder */
    private Builder() {
      super(avro.extlibrary.Borrower.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.extlibrary.Borrower.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.address)) {
        this.address = data().deepCopy(fields()[0].schema(), other.address);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.firstName)) {
        this.firstName = data().deepCopy(fields()[1].schema(), other.firstName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastName)) {
        this.lastName = data().deepCopy(fields()[2].schema(), other.lastName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.borrowed)) {
        this.borrowed = data().deepCopy(fields()[3].schema(), other.borrowed);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Borrower instance */
    private Builder(avro.extlibrary.Borrower other) {
            super(avro.extlibrary.Borrower.SCHEMA$);
      if (isValidValue(fields()[0], other.address)) {
        this.address = data().deepCopy(fields()[0].schema(), other.address);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.firstName)) {
        this.firstName = data().deepCopy(fields()[1].schema(), other.firstName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastName)) {
        this.lastName = data().deepCopy(fields()[2].schema(), other.lastName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.borrowed)) {
        this.borrowed = data().deepCopy(fields()[3].schema(), other.borrowed);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'address' field */
    public java.lang.CharSequence getAddress() {
      return address;
    }
    
    /** Sets the value of the 'address' field */
    public avro.extlibrary.Borrower.Builder setAddress(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.address = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'address' field has been set */
    public boolean hasAddress() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'address' field */
    public avro.extlibrary.Borrower.Builder clearAddress() {
      address = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'firstName' field */
    public java.lang.CharSequence getFirstName() {
      return firstName;
    }
    
    /** Sets the value of the 'firstName' field */
    public avro.extlibrary.Borrower.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.firstName = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'firstName' field has been set */
    public boolean hasFirstName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'firstName' field */
    public avro.extlibrary.Borrower.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'lastName' field */
    public java.lang.CharSequence getLastName() {
      return lastName;
    }
    
    /** Sets the value of the 'lastName' field */
    public avro.extlibrary.Borrower.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.lastName = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'lastName' field has been set */
    public boolean hasLastName() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'lastName' field */
    public avro.extlibrary.Borrower.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'borrowed' field */
    public java.util.List<avro.extlibrary.Lendable> getBorrowed() {
      return borrowed;
    }
    
    /** Sets the value of the 'borrowed' field */
    public avro.extlibrary.Borrower.Builder setBorrowed(java.util.List<avro.extlibrary.Lendable> value) {
      validate(fields()[3], value);
      this.borrowed = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'borrowed' field has been set */
    public boolean hasBorrowed() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'borrowed' field */
    public avro.extlibrary.Borrower.Builder clearBorrowed() {
      borrowed = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public Borrower build() {
      try {
        Borrower record = new Borrower();
        record.address = fieldSetFlags()[0] ? this.address : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.firstName = fieldSetFlags()[1] ? this.firstName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.lastName = fieldSetFlags()[2] ? this.lastName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.borrowed = fieldSetFlags()[3] ? this.borrowed : (java.util.List<avro.extlibrary.Lendable>) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
