/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.extlibrary;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Periodical extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Periodical\",\"namespace\":\"avro.extlibrary\",\"fields\":[{\"name\":\"publicationDate\",\"type\":\"string\"},{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"issuesPerYear\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence publicationDate;
  @Deprecated public java.lang.CharSequence title;
  @Deprecated public int issuesPerYear;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public Periodical() {}

  /**
   * All-args constructor.
   */
  public Periodical(java.lang.CharSequence publicationDate, java.lang.CharSequence title, java.lang.Integer issuesPerYear) {
    this.publicationDate = publicationDate;
    this.title = title;
    this.issuesPerYear = issuesPerYear;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return publicationDate;
    case 1: return title;
    case 2: return issuesPerYear;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: publicationDate = (java.lang.CharSequence)value$; break;
    case 1: title = (java.lang.CharSequence)value$; break;
    case 2: issuesPerYear = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'publicationDate' field.
   */
  public java.lang.CharSequence getPublicationDate() {
    return publicationDate;
  }

  /**
   * Sets the value of the 'publicationDate' field.
   * @param value the value to set.
   */
  public void setPublicationDate(java.lang.CharSequence value) {
    this.publicationDate = value;
  }

  /**
   * Gets the value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }

  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'issuesPerYear' field.
   */
  public java.lang.Integer getIssuesPerYear() {
    return issuesPerYear;
  }

  /**
   * Sets the value of the 'issuesPerYear' field.
   * @param value the value to set.
   */
  public void setIssuesPerYear(java.lang.Integer value) {
    this.issuesPerYear = value;
  }

  /** Creates a new Periodical RecordBuilder */
  public static avro.extlibrary.Periodical.Builder newBuilder() {
    return new avro.extlibrary.Periodical.Builder();
  }
  
  /** Creates a new Periodical RecordBuilder by copying an existing Builder */
  public static avro.extlibrary.Periodical.Builder newBuilder(avro.extlibrary.Periodical.Builder other) {
    return new avro.extlibrary.Periodical.Builder(other);
  }
  
  /** Creates a new Periodical RecordBuilder by copying an existing Periodical instance */
  public static avro.extlibrary.Periodical.Builder newBuilder(avro.extlibrary.Periodical other) {
    return new avro.extlibrary.Periodical.Builder(other);
  }
  
  /**
   * RecordBuilder for Periodical instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Periodical>
    implements org.apache.avro.data.RecordBuilder<Periodical> {

    private java.lang.CharSequence publicationDate;
    private java.lang.CharSequence title;
    private int issuesPerYear;

    /** Creates a new Builder */
    private Builder() {
      super(avro.extlibrary.Periodical.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.extlibrary.Periodical.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.publicationDate)) {
        this.publicationDate = data().deepCopy(fields()[0].schema(), other.publicationDate);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.issuesPerYear)) {
        this.issuesPerYear = data().deepCopy(fields()[2].schema(), other.issuesPerYear);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Periodical instance */
    private Builder(avro.extlibrary.Periodical other) {
            super(avro.extlibrary.Periodical.SCHEMA$);
      if (isValidValue(fields()[0], other.publicationDate)) {
        this.publicationDate = data().deepCopy(fields()[0].schema(), other.publicationDate);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.issuesPerYear)) {
        this.issuesPerYear = data().deepCopy(fields()[2].schema(), other.issuesPerYear);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'publicationDate' field */
    public java.lang.CharSequence getPublicationDate() {
      return publicationDate;
    }
    
    /** Sets the value of the 'publicationDate' field */
    public avro.extlibrary.Periodical.Builder setPublicationDate(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.publicationDate = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'publicationDate' field has been set */
    public boolean hasPublicationDate() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'publicationDate' field */
    public avro.extlibrary.Periodical.Builder clearPublicationDate() {
      publicationDate = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'title' field */
    public java.lang.CharSequence getTitle() {
      return title;
    }
    
    /** Sets the value of the 'title' field */
    public avro.extlibrary.Periodical.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.title = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'title' field has been set */
    public boolean hasTitle() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'title' field */
    public avro.extlibrary.Periodical.Builder clearTitle() {
      title = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'issuesPerYear' field */
    public java.lang.Integer getIssuesPerYear() {
      return issuesPerYear;
    }
    
    /** Sets the value of the 'issuesPerYear' field */
    public avro.extlibrary.Periodical.Builder setIssuesPerYear(int value) {
      validate(fields()[2], value);
      this.issuesPerYear = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'issuesPerYear' field has been set */
    public boolean hasIssuesPerYear() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'issuesPerYear' field */
    public avro.extlibrary.Periodical.Builder clearIssuesPerYear() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Periodical build() {
      try {
        Periodical record = new Periodical();
        record.publicationDate = fieldSetFlags()[0] ? this.publicationDate : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.title = fieldSetFlags()[1] ? this.title : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.issuesPerYear = fieldSetFlags()[2] ? this.issuesPerYear : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
