/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.extlibrary;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class VideoCassette extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"VideoCassette\",\"namespace\":\"avro.extlibrary\",\"fields\":[{\"name\":\"publicationDate\",\"type\":\"string\"},{\"name\":\"copies\",\"type\":\"int\"},{\"name\":\"borrowers\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Borrower\",\"fields\":[{\"name\":\"address\",\"type\":\"string\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"borrowed\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Lendable\",\"fields\":[{\"name\":\"copies\",\"type\":\"int\"},{\"name\":\"borrowers\",\"type\":{\"type\":\"array\",\"items\":\"Borrower\"}}]}}}]}}},{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"minutesLength\",\"type\":\"int\"},{\"name\":\"damaged\",\"type\":\"boolean\"},{\"name\":\"cast\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Person\",\"fields\":[{\"name\":\"address\",\"type\":\"string\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence publicationDate;
  @Deprecated public int copies;
  @Deprecated public java.util.List<avro.extlibrary.Borrower> borrowers;
  @Deprecated public java.lang.CharSequence title;
  @Deprecated public int minutesLength;
  @Deprecated public boolean damaged;
  @Deprecated public java.util.List<avro.extlibrary.Person> cast;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public VideoCassette() {}

  /**
   * All-args constructor.
   */
  public VideoCassette(java.lang.CharSequence publicationDate, java.lang.Integer copies, java.util.List<avro.extlibrary.Borrower> borrowers, java.lang.CharSequence title, java.lang.Integer minutesLength, java.lang.Boolean damaged, java.util.List<avro.extlibrary.Person> cast) {
    this.publicationDate = publicationDate;
    this.copies = copies;
    this.borrowers = borrowers;
    this.title = title;
    this.minutesLength = minutesLength;
    this.damaged = damaged;
    this.cast = cast;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return publicationDate;
    case 1: return copies;
    case 2: return borrowers;
    case 3: return title;
    case 4: return minutesLength;
    case 5: return damaged;
    case 6: return cast;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: publicationDate = (java.lang.CharSequence)value$; break;
    case 1: copies = (java.lang.Integer)value$; break;
    case 2: borrowers = (java.util.List<avro.extlibrary.Borrower>)value$; break;
    case 3: title = (java.lang.CharSequence)value$; break;
    case 4: minutesLength = (java.lang.Integer)value$; break;
    case 5: damaged = (java.lang.Boolean)value$; break;
    case 6: cast = (java.util.List<avro.extlibrary.Person>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'publicationDate' field.
   */
  public java.lang.CharSequence getPublicationDate() {
    return publicationDate;
  }

  /**
   * Sets the value of the 'publicationDate' field.
   * @param value the value to set.
   */
  public void setPublicationDate(java.lang.CharSequence value) {
    this.publicationDate = value;
  }

  /**
   * Gets the value of the 'copies' field.
   */
  public java.lang.Integer getCopies() {
    return copies;
  }

  /**
   * Sets the value of the 'copies' field.
   * @param value the value to set.
   */
  public void setCopies(java.lang.Integer value) {
    this.copies = value;
  }

  /**
   * Gets the value of the 'borrowers' field.
   */
  public java.util.List<avro.extlibrary.Borrower> getBorrowers() {
    return borrowers;
  }

  /**
   * Sets the value of the 'borrowers' field.
   * @param value the value to set.
   */
  public void setBorrowers(java.util.List<avro.extlibrary.Borrower> value) {
    this.borrowers = value;
  }

  /**
   * Gets the value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }

  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'minutesLength' field.
   */
  public java.lang.Integer getMinutesLength() {
    return minutesLength;
  }

  /**
   * Sets the value of the 'minutesLength' field.
   * @param value the value to set.
   */
  public void setMinutesLength(java.lang.Integer value) {
    this.minutesLength = value;
  }

  /**
   * Gets the value of the 'damaged' field.
   */
  public java.lang.Boolean getDamaged() {
    return damaged;
  }

  /**
   * Sets the value of the 'damaged' field.
   * @param value the value to set.
   */
  public void setDamaged(java.lang.Boolean value) {
    this.damaged = value;
  }

  /**
   * Gets the value of the 'cast' field.
   */
  public java.util.List<avro.extlibrary.Person> getCast() {
    return cast;
  }

  /**
   * Sets the value of the 'cast' field.
   * @param value the value to set.
   */
  public void setCast(java.util.List<avro.extlibrary.Person> value) {
    this.cast = value;
  }

  /** Creates a new VideoCassette RecordBuilder */
  public static avro.extlibrary.VideoCassette.Builder newBuilder() {
    return new avro.extlibrary.VideoCassette.Builder();
  }
  
  /** Creates a new VideoCassette RecordBuilder by copying an existing Builder */
  public static avro.extlibrary.VideoCassette.Builder newBuilder(avro.extlibrary.VideoCassette.Builder other) {
    return new avro.extlibrary.VideoCassette.Builder(other);
  }
  
  /** Creates a new VideoCassette RecordBuilder by copying an existing VideoCassette instance */
  public static avro.extlibrary.VideoCassette.Builder newBuilder(avro.extlibrary.VideoCassette other) {
    return new avro.extlibrary.VideoCassette.Builder(other);
  }
  
  /**
   * RecordBuilder for VideoCassette instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<VideoCassette>
    implements org.apache.avro.data.RecordBuilder<VideoCassette> {

    private java.lang.CharSequence publicationDate;
    private int copies;
    private java.util.List<avro.extlibrary.Borrower> borrowers;
    private java.lang.CharSequence title;
    private int minutesLength;
    private boolean damaged;
    private java.util.List<avro.extlibrary.Person> cast;

    /** Creates a new Builder */
    private Builder() {
      super(avro.extlibrary.VideoCassette.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.extlibrary.VideoCassette.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.publicationDate)) {
        this.publicationDate = data().deepCopy(fields()[0].schema(), other.publicationDate);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.copies)) {
        this.copies = data().deepCopy(fields()[1].schema(), other.copies);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.borrowers)) {
        this.borrowers = data().deepCopy(fields()[2].schema(), other.borrowers);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.title)) {
        this.title = data().deepCopy(fields()[3].schema(), other.title);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.minutesLength)) {
        this.minutesLength = data().deepCopy(fields()[4].schema(), other.minutesLength);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.damaged)) {
        this.damaged = data().deepCopy(fields()[5].schema(), other.damaged);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.cast)) {
        this.cast = data().deepCopy(fields()[6].schema(), other.cast);
        fieldSetFlags()[6] = true;
      }
    }
    
    /** Creates a Builder by copying an existing VideoCassette instance */
    private Builder(avro.extlibrary.VideoCassette other) {
            super(avro.extlibrary.VideoCassette.SCHEMA$);
      if (isValidValue(fields()[0], other.publicationDate)) {
        this.publicationDate = data().deepCopy(fields()[0].schema(), other.publicationDate);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.copies)) {
        this.copies = data().deepCopy(fields()[1].schema(), other.copies);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.borrowers)) {
        this.borrowers = data().deepCopy(fields()[2].schema(), other.borrowers);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.title)) {
        this.title = data().deepCopy(fields()[3].schema(), other.title);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.minutesLength)) {
        this.minutesLength = data().deepCopy(fields()[4].schema(), other.minutesLength);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.damaged)) {
        this.damaged = data().deepCopy(fields()[5].schema(), other.damaged);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.cast)) {
        this.cast = data().deepCopy(fields()[6].schema(), other.cast);
        fieldSetFlags()[6] = true;
      }
    }

    /** Gets the value of the 'publicationDate' field */
    public java.lang.CharSequence getPublicationDate() {
      return publicationDate;
    }
    
    /** Sets the value of the 'publicationDate' field */
    public avro.extlibrary.VideoCassette.Builder setPublicationDate(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.publicationDate = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'publicationDate' field has been set */
    public boolean hasPublicationDate() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'publicationDate' field */
    public avro.extlibrary.VideoCassette.Builder clearPublicationDate() {
      publicationDate = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'copies' field */
    public java.lang.Integer getCopies() {
      return copies;
    }
    
    /** Sets the value of the 'copies' field */
    public avro.extlibrary.VideoCassette.Builder setCopies(int value) {
      validate(fields()[1], value);
      this.copies = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'copies' field has been set */
    public boolean hasCopies() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'copies' field */
    public avro.extlibrary.VideoCassette.Builder clearCopies() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'borrowers' field */
    public java.util.List<avro.extlibrary.Borrower> getBorrowers() {
      return borrowers;
    }
    
    /** Sets the value of the 'borrowers' field */
    public avro.extlibrary.VideoCassette.Builder setBorrowers(java.util.List<avro.extlibrary.Borrower> value) {
      validate(fields()[2], value);
      this.borrowers = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'borrowers' field has been set */
    public boolean hasBorrowers() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'borrowers' field */
    public avro.extlibrary.VideoCassette.Builder clearBorrowers() {
      borrowers = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'title' field */
    public java.lang.CharSequence getTitle() {
      return title;
    }
    
    /** Sets the value of the 'title' field */
    public avro.extlibrary.VideoCassette.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.title = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'title' field has been set */
    public boolean hasTitle() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'title' field */
    public avro.extlibrary.VideoCassette.Builder clearTitle() {
      title = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'minutesLength' field */
    public java.lang.Integer getMinutesLength() {
      return minutesLength;
    }
    
    /** Sets the value of the 'minutesLength' field */
    public avro.extlibrary.VideoCassette.Builder setMinutesLength(int value) {
      validate(fields()[4], value);
      this.minutesLength = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'minutesLength' field has been set */
    public boolean hasMinutesLength() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'minutesLength' field */
    public avro.extlibrary.VideoCassette.Builder clearMinutesLength() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'damaged' field */
    public java.lang.Boolean getDamaged() {
      return damaged;
    }
    
    /** Sets the value of the 'damaged' field */
    public avro.extlibrary.VideoCassette.Builder setDamaged(boolean value) {
      validate(fields()[5], value);
      this.damaged = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'damaged' field has been set */
    public boolean hasDamaged() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'damaged' field */
    public avro.extlibrary.VideoCassette.Builder clearDamaged() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'cast' field */
    public java.util.List<avro.extlibrary.Person> getCast() {
      return cast;
    }
    
    /** Sets the value of the 'cast' field */
    public avro.extlibrary.VideoCassette.Builder setCast(java.util.List<avro.extlibrary.Person> value) {
      validate(fields()[6], value);
      this.cast = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'cast' field has been set */
    public boolean hasCast() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'cast' field */
    public avro.extlibrary.VideoCassette.Builder clearCast() {
      cast = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public VideoCassette build() {
      try {
        VideoCassette record = new VideoCassette();
        record.publicationDate = fieldSetFlags()[0] ? this.publicationDate : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.copies = fieldSetFlags()[1] ? this.copies : (java.lang.Integer) defaultValue(fields()[1]);
        record.borrowers = fieldSetFlags()[2] ? this.borrowers : (java.util.List<avro.extlibrary.Borrower>) defaultValue(fields()[2]);
        record.title = fieldSetFlags()[3] ? this.title : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.minutesLength = fieldSetFlags()[4] ? this.minutesLength : (java.lang.Integer) defaultValue(fields()[4]);
        record.damaged = fieldSetFlags()[5] ? this.damaged : (java.lang.Boolean) defaultValue(fields()[5]);
        record.cast = fieldSetFlags()[6] ? this.cast : (java.util.List<avro.extlibrary.Person>) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
