/*
 * generated by Xtext
 */
package net.langleystudios.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AvroSchemaRuntimeModule extends net.langleystudios.dsl.AbstractAvroSchemaRuntimeModule {

}
