/*
* generated by Xtext
*/
package net.langleystudios.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AvroSchemaStandaloneSetup extends AvroSchemaStandaloneSetupGenerated{

	public static void doSetup() {
		new AvroSchemaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

