/*
 * generated by Xtext
 */
package net.langleystudios.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AvroSchemaUiModule extends net.langleystudios.dsl.ui.AbstractAvroSchemaUiModule {
	public AvroSchemaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
