/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.eclipse.emf.examples.extlibrary.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Addressable extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Addressable\",\"namespace\":\"org.eclipse.emf.examples.extlibrary.avro\",\"fields\":[{\"name\":\"address\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence address;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Addressable() {}

  /**
   * All-args constructor.
   */
  public Addressable(java.lang.CharSequence address) {
    this.address = address;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return address;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: address = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'address' field.
   */
  public java.lang.CharSequence getAddress() {
    return address;
  }

  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(java.lang.CharSequence value) {
    this.address = value;
  }

  /** Creates a new Addressable RecordBuilder */
  public static org.eclipse.emf.examples.extlibrary.avro.Addressable.Builder newBuilder() {
    return new org.eclipse.emf.examples.extlibrary.avro.Addressable.Builder();
  }
  
  /** Creates a new Addressable RecordBuilder by copying an existing Builder */
  public static org.eclipse.emf.examples.extlibrary.avro.Addressable.Builder newBuilder(org.eclipse.emf.examples.extlibrary.avro.Addressable.Builder other) {
    return new org.eclipse.emf.examples.extlibrary.avro.Addressable.Builder(other);
  }
  
  /** Creates a new Addressable RecordBuilder by copying an existing Addressable instance */
  public static org.eclipse.emf.examples.extlibrary.avro.Addressable.Builder newBuilder(org.eclipse.emf.examples.extlibrary.avro.Addressable other) {
    return new org.eclipse.emf.examples.extlibrary.avro.Addressable.Builder(other);
  }
  
  /**
   * RecordBuilder for Addressable instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Addressable>
    implements org.apache.avro.data.RecordBuilder<Addressable> {

    private java.lang.CharSequence address;

    /** Creates a new Builder */
    private Builder() {
      super(org.eclipse.emf.examples.extlibrary.avro.Addressable.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.eclipse.emf.examples.extlibrary.avro.Addressable.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.address)) {
        this.address = data().deepCopy(fields()[0].schema(), other.address);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Addressable instance */
    private Builder(org.eclipse.emf.examples.extlibrary.avro.Addressable other) {
            super(org.eclipse.emf.examples.extlibrary.avro.Addressable.SCHEMA$);
      if (isValidValue(fields()[0], other.address)) {
        this.address = data().deepCopy(fields()[0].schema(), other.address);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'address' field */
    public java.lang.CharSequence getAddress() {
      return address;
    }
    
    /** Sets the value of the 'address' field */
    public org.eclipse.emf.examples.extlibrary.avro.Addressable.Builder setAddress(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.address = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'address' field has been set */
    public boolean hasAddress() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'address' field */
    public org.eclipse.emf.examples.extlibrary.avro.Addressable.Builder clearAddress() {
      address = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public Addressable build() {
      try {
        Addressable record = new Addressable();
        record.address = fieldSetFlags()[0] ? this.address : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
