/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.eclipse.emf.examples.extlibrary.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AudioVisualItem extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AudioVisualItem\",\"namespace\":\"org.eclipse.emf.examples.extlibrary.avro\",\"fields\":[{\"name\":\"publicationDate\",\"type\":[\"null\",\"string\"]},{\"name\":\"copies\",\"type\":\"int\"},{\"name\":\"borrowers\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}]},{\"name\":\"title\",\"type\":[\"null\",\"string\"]},{\"name\":\"minutesLength\",\"type\":\"int\"},{\"name\":\"damaged\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence publicationDate;
  @Deprecated public int copies;
  @Deprecated public java.util.List<java.lang.CharSequence> borrowers;
  @Deprecated public java.lang.CharSequence title;
  @Deprecated public int minutesLength;
  @Deprecated public boolean damaged;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public AudioVisualItem() {}

  /**
   * All-args constructor.
   */
  public AudioVisualItem(java.lang.CharSequence publicationDate, java.lang.Integer copies, java.util.List<java.lang.CharSequence> borrowers, java.lang.CharSequence title, java.lang.Integer minutesLength, java.lang.Boolean damaged) {
    this.publicationDate = publicationDate;
    this.copies = copies;
    this.borrowers = borrowers;
    this.title = title;
    this.minutesLength = minutesLength;
    this.damaged = damaged;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return publicationDate;
    case 1: return copies;
    case 2: return borrowers;
    case 3: return title;
    case 4: return minutesLength;
    case 5: return damaged;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: publicationDate = (java.lang.CharSequence)value$; break;
    case 1: copies = (java.lang.Integer)value$; break;
    case 2: borrowers = (java.util.List<java.lang.CharSequence>)value$; break;
    case 3: title = (java.lang.CharSequence)value$; break;
    case 4: minutesLength = (java.lang.Integer)value$; break;
    case 5: damaged = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'publicationDate' field.
   */
  public java.lang.CharSequence getPublicationDate() {
    return publicationDate;
  }

  /**
   * Sets the value of the 'publicationDate' field.
   * @param value the value to set.
   */
  public void setPublicationDate(java.lang.CharSequence value) {
    this.publicationDate = value;
  }

  /**
   * Gets the value of the 'copies' field.
   */
  public java.lang.Integer getCopies() {
    return copies;
  }

  /**
   * Sets the value of the 'copies' field.
   * @param value the value to set.
   */
  public void setCopies(java.lang.Integer value) {
    this.copies = value;
  }

  /**
   * Gets the value of the 'borrowers' field.
   */
  public java.util.List<java.lang.CharSequence> getBorrowers() {
    return borrowers;
  }

  /**
   * Sets the value of the 'borrowers' field.
   * @param value the value to set.
   */
  public void setBorrowers(java.util.List<java.lang.CharSequence> value) {
    this.borrowers = value;
  }

  /**
   * Gets the value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }

  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'minutesLength' field.
   */
  public java.lang.Integer getMinutesLength() {
    return minutesLength;
  }

  /**
   * Sets the value of the 'minutesLength' field.
   * @param value the value to set.
   */
  public void setMinutesLength(java.lang.Integer value) {
    this.minutesLength = value;
  }

  /**
   * Gets the value of the 'damaged' field.
   */
  public java.lang.Boolean getDamaged() {
    return damaged;
  }

  /**
   * Sets the value of the 'damaged' field.
   * @param value the value to set.
   */
  public void setDamaged(java.lang.Boolean value) {
    this.damaged = value;
  }

  /** Creates a new AudioVisualItem RecordBuilder */
  public static org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder newBuilder() {
    return new org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder();
  }
  
  /** Creates a new AudioVisualItem RecordBuilder by copying an existing Builder */
  public static org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder newBuilder(org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder other) {
    return new org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder(other);
  }
  
  /** Creates a new AudioVisualItem RecordBuilder by copying an existing AudioVisualItem instance */
  public static org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder newBuilder(org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem other) {
    return new org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder(other);
  }
  
  /**
   * RecordBuilder for AudioVisualItem instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AudioVisualItem>
    implements org.apache.avro.data.RecordBuilder<AudioVisualItem> {

    private java.lang.CharSequence publicationDate;
    private int copies;
    private java.util.List<java.lang.CharSequence> borrowers;
    private java.lang.CharSequence title;
    private int minutesLength;
    private boolean damaged;

    /** Creates a new Builder */
    private Builder() {
      super(org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.publicationDate)) {
        this.publicationDate = data().deepCopy(fields()[0].schema(), other.publicationDate);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.copies)) {
        this.copies = data().deepCopy(fields()[1].schema(), other.copies);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.borrowers)) {
        this.borrowers = data().deepCopy(fields()[2].schema(), other.borrowers);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.title)) {
        this.title = data().deepCopy(fields()[3].schema(), other.title);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.minutesLength)) {
        this.minutesLength = data().deepCopy(fields()[4].schema(), other.minutesLength);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.damaged)) {
        this.damaged = data().deepCopy(fields()[5].schema(), other.damaged);
        fieldSetFlags()[5] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AudioVisualItem instance */
    private Builder(org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem other) {
            super(org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.SCHEMA$);
      if (isValidValue(fields()[0], other.publicationDate)) {
        this.publicationDate = data().deepCopy(fields()[0].schema(), other.publicationDate);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.copies)) {
        this.copies = data().deepCopy(fields()[1].schema(), other.copies);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.borrowers)) {
        this.borrowers = data().deepCopy(fields()[2].schema(), other.borrowers);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.title)) {
        this.title = data().deepCopy(fields()[3].schema(), other.title);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.minutesLength)) {
        this.minutesLength = data().deepCopy(fields()[4].schema(), other.minutesLength);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.damaged)) {
        this.damaged = data().deepCopy(fields()[5].schema(), other.damaged);
        fieldSetFlags()[5] = true;
      }
    }

    /** Gets the value of the 'publicationDate' field */
    public java.lang.CharSequence getPublicationDate() {
      return publicationDate;
    }
    
    /** Sets the value of the 'publicationDate' field */
    public org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder setPublicationDate(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.publicationDate = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'publicationDate' field has been set */
    public boolean hasPublicationDate() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'publicationDate' field */
    public org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder clearPublicationDate() {
      publicationDate = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'copies' field */
    public java.lang.Integer getCopies() {
      return copies;
    }
    
    /** Sets the value of the 'copies' field */
    public org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder setCopies(int value) {
      validate(fields()[1], value);
      this.copies = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'copies' field has been set */
    public boolean hasCopies() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'copies' field */
    public org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder clearCopies() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'borrowers' field */
    public java.util.List<java.lang.CharSequence> getBorrowers() {
      return borrowers;
    }
    
    /** Sets the value of the 'borrowers' field */
    public org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder setBorrowers(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[2], value);
      this.borrowers = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'borrowers' field has been set */
    public boolean hasBorrowers() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'borrowers' field */
    public org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder clearBorrowers() {
      borrowers = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'title' field */
    public java.lang.CharSequence getTitle() {
      return title;
    }
    
    /** Sets the value of the 'title' field */
    public org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.title = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'title' field has been set */
    public boolean hasTitle() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'title' field */
    public org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder clearTitle() {
      title = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'minutesLength' field */
    public java.lang.Integer getMinutesLength() {
      return minutesLength;
    }
    
    /** Sets the value of the 'minutesLength' field */
    public org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder setMinutesLength(int value) {
      validate(fields()[4], value);
      this.minutesLength = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'minutesLength' field has been set */
    public boolean hasMinutesLength() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'minutesLength' field */
    public org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder clearMinutesLength() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'damaged' field */
    public java.lang.Boolean getDamaged() {
      return damaged;
    }
    
    /** Sets the value of the 'damaged' field */
    public org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder setDamaged(boolean value) {
      validate(fields()[5], value);
      this.damaged = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'damaged' field has been set */
    public boolean hasDamaged() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'damaged' field */
    public org.eclipse.emf.examples.extlibrary.avro.AudioVisualItem.Builder clearDamaged() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public AudioVisualItem build() {
      try {
        AudioVisualItem record = new AudioVisualItem();
        record.publicationDate = fieldSetFlags()[0] ? this.publicationDate : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.copies = fieldSetFlags()[1] ? this.copies : (java.lang.Integer) defaultValue(fields()[1]);
        record.borrowers = fieldSetFlags()[2] ? this.borrowers : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[2]);
        record.title = fieldSetFlags()[3] ? this.title : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.minutesLength = fieldSetFlags()[4] ? this.minutesLength : (java.lang.Integer) defaultValue(fields()[4]);
        record.damaged = fieldSetFlags()[5] ? this.damaged : (java.lang.Boolean) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
